---
- name: Remove Specific packages using Chocolatey
  hosts: all
  gather_facts: false
  vars:
    choco_packages:
      - name: nodejs
        version: 13.0.0
      - name: python
        version: 3.6.0
  tasks:
    - name: Remove specific versions of packages sequentially
      chocolatey.chocolatey.win_chocolatey:
        name: "{{ item.name }}"
        state: absent
      loop: "{{ choco_packages }}"
